let county = [
    { "city_sid": "1", "city_name": "台北市" },
    { "city_sid": "2", "city_name": "新北市" },
    { "city_sid": "3", "city_name": "基隆市" },
]

let area = [
    { "area_sid": "1", "city_sid": "1", "area_name": "中正區" },
    { "area_sid": "2", "city_sid": "1", "area_name": "大同區" },
    { "area_sid": "3", "city_sid": "1", "area_name": "中山區" },
    { "area_sid": "4", "city_sid": "1", "area_name": "松山區" },
    { "area_sid": "5", "city_sid": "1", "area_name": "大安區" },
    { "area_sid": "6", "city_sid": "1", "area_name": "萬華區" },
    { "area_sid": "7", "city_sid": "1", "area_name": "信義區" },
    { "area_sid": "8", "city_sid": "1", "area_name": "士林區" },
    { "area_sid": "9", "city_sid": "1", "area_name": "北投區" },
    { "area_sid": "10", "city_sid": "1", "area_name": "內湖區" },
    { "area_sid": "11", "city_sid": "1", "area_name": "南港區" },
    { "area_sid": "12", "city_sid": "1", "area_name": "文山區" },
    { "area_sid": "13", "city_sid": "2", "area_name": "萬里區" },
    { "area_sid": "14", "city_sid": "2", "area_name": "金山區" },
    { "area_sid": "15", "city_sid": "2", "area_name": "板橋區" },
    { "area_sid": "16", "city_sid": "2", "area_name": "汐止區" },
    { "area_sid": "17", "city_sid": "2", "area_name": "深坑區" },
    { "area_sid": "18", "city_sid": "2", "area_name": "石碇區" },
    { "area_sid": "19", "city_sid": "2", "area_name": "瑞芳區" },
    { "area_sid": "20", "city_sid": "2", "area_name": "平溪區" },
    { "area_sid": "21", "city_sid": "2", "area_name": "雙溪區" },
    { "area_sid": "22", "city_sid": "2", "area_name": "貢寮區" },
    { "area_sid": "23", "city_sid": "2", "area_name": "新店區" },
    { "area_sid": "24", "city_sid": "2", "area_name": "坪林區" },
    { "area_sid": "25", "city_sid": "2", "area_name": "烏來區" },
    { "area_sid": "26", "city_sid": "2", "area_name": "永和區" },
    { "area_sid": "27", "city_sid": "2", "area_name": "中和區" },
    { "area_sid": "28", "city_sid": "2", "area_name": "土城區" },
    { "area_sid": "29", "city_sid": "2", "area_name": "三峽區" },
    { "area_sid": "30", "city_sid": "2", "area_name": "樹林區" },
    { "area_sid": "31", "city_sid": "2", "area_name": "鶯歌區" },
    { "area_sid": "32", "city_sid": "2", "area_name": "三重區" },
    { "area_sid": "33", "city_sid": "2", "area_name": "新莊區" },
    { "area_sid": "34", "city_sid": "2", "area_name": "泰山區" },
    { "area_sid": "35", "city_sid": "2", "area_name": "林口區" },
    { "area_sid": "36", "city_sid": "2", "area_name": "蘆洲區" },
    { "area_sid": "37", "city_sid": "2", "area_name": "五股區" },
    { "area_sid": "38", "city_sid": "2", "area_name": "八里區" },
    { "area_sid": "39", "city_sid": "2", "area_name": "淡水區" },
    { "area_sid": "40", "city_sid": "2", "area_name": "三芝區" },
    { "area_sid": "41", "city_sid": "2", "area_name": "石門區" },
    { "area_sid": "42", "city_sid": "3", "area_name": "仁愛區" },
    { "area_sid": "43", "city_sid": "3", "area_name": "信義區" },
    { "area_sid": "44", "city_sid": "3", "area_name": "中正區" },
    { "area_sid": "45", "city_sid": "3", "area_name": "中山區" },
    { "area_sid": "46", "city_sid": "3", "area_name": "安樂區" },
    { "area_sid": "47", "city_sid": "3", "area_name": "暖暖區" },
    { "area_sid": "48", "city_sid": "3", "area_name": "七堵區" }
]
